pipeline {
  agent any
  tools {
    nodejs "node"
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {        
        sh 'echo hola'
      }
    }
    stage('Run tests') {
      steps {
        sh 'echo hola2'        
      }
    }
  }
}
