pipeline {
  agent any    

  stages {
    stage('Install dependencies') {
      steps {
        sh 'echo hola'
      }
    }
    stage('Run tests') {
      steps {
        sh 'echo hola2'
      }
    }
  }
}
